# Generated by Django 3.2.7 on 2021-09-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptopname', models.CharField(max_length=30)),
                ('laptopCompany', models.CharField(max_length=30)),
                ('laptopram', models.IntegerField()),
                ('laptoprom', models.IntegerField()),
                ('laptopprice', models.IntegerField()),
                ('laptopprocessor', models.CharField(max_length=30)),
            ],
        ),
    ]
